#!/usr/bin/env sh

COMMAND=${1:-add}
FOLLOW=$(if [ "${COMMAND}" = "add" ]; then echo "^"; else echo ""; fi)

yabai -m config external_bar main:0:0

# space 2: web
yabai -m rule --${COMMAND} app="Safari" space=${FOLLOW}2
